_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
stage:
    value: lifelong
warm_up_attack_log:
    value: []
